### ISSUE TITLE
Doesn't work with strings

### ISSUE THREAD

**Issue by onbjerg** [pull-stream/pull-write-file#2]
In order for it to work with strings one must manually convert strings to buffers before passing them to this module.

**Comment by dominictarr** [comment]
I'd happly merge a pull request that added support for other encodings, in a way that is compatible with node's fs write stream.

**Comment by onbjerg** [comment]
Sure. The README says it accepts strings though, so I assumed this was already supported 😁

**Comment by dominictarr** [comment]
oh i see it, but it also says "currently really simple and does not yet support all fs.createWriteStream options yet."
